version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: callact_db_container
    environment:
      POSTGRES_USER: callact_admin
      POSTGRES_PASSWORD: callact_pwd1
      POSTGRES_DB: callact_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U callact_admin -d callact_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


